### ISSUE TITLE
`make install` currently only installs LICENSE

### ISSUE THREAD

**Issue by kdheepak** [GMLC-TDC/HELICS#1081]
It should install LICENSE, NOTICE, DISCLAIMER and README.md.

**Comment by nightlark** [comment]
With the default options on Linux I'm seeing a `make install` put LICENSE, NOTICE, README.md, CHANGELOG.md, and third party licenses in `share/doc/HELICS`.

I seem to remember some talk about if DISCLAIMER needs to be included -- I think not including it is because the first several lines of NOTICE are the exact same text as the DISCLAIMER.

**Comment by nightlark** [comment]
Previous discussion about the legal files: https://github.com/GMLC-TDC/HELICS/pull/621#issuecomment-461908750

**Comment by nightlark** [comment]
Tried v2.4.0 on macOS with the default CMake options, I'm seeing the same set of files installed in `share/doc/HELICS` as on Linux.

What options did you use? I'm not able to reproduce the LICENSE only issue using the defaults.

**Comment by kdheepak** [comment]
I was looking in the licenses folder, which might be a Julia Binary Builder thing.

```
└── share
   ├── doc
   │  └── HELICS
   │     ├── CHANGELOG.md
   │     ├── LICENSE
   │     ├── NOTICE
   │     ├── README.md
   │     └── THIRDPARTY_LICENSES
   ├── helics
   │  └── swig
   │     └── helics.i
   ├── licenses
   │  └── libhelicsSharedLib
   │     └── LICENSE
```

All the files are in `share/doc/HELICS`. I'll close this issue.
