### ISSUE TITLE
Wnat does cmd:unknown mean in the helics_broker log?

### ISSUE THREAD

**Issue by temcdrm** [GMLC-TDC/HELICS#1174]
I'm trying to gather clues on a deadlock problem, and found this in the output from loglevel 7 on the broker:

_mainbroker (1)::|| cmd:time_grant:From (1879048192) Granted Time(0.0) to (1) from 1879048192 to 1
mainbroker (1)::|| **cmd:unknown 6** from 131072 to 0_

Sometimes, the 6 is 211.  It seems like an error; how can I track down the origin and cause of this message?

It may have something to do with filters.  I have variants of my example running with pub/sub values, and also with endpoints.  However, the endpoint variant hangs when I add either _ns3_, or the _helics_recorder_ with a _sourceclone_ on an endpoint.  Both of those add-ons involve a filter, because the _helics_recorder_ implements _sourceclone_ by creating a filter along with another endpoint. In my logfile snippet above, I think 1879048192 is the clone endpoint while 131072 is the recorder itself. Compared to the pub/sub version, I've noticed that the created clone endpoint makes time requests, but the recorder itself does not. The _helics_recorder_ works fine in my pub/sub variant, and makes its own time requests.  So, I've tried a bunch of different things with timing, but would also like to rule out the possible significance of **cmd:unknown**.

Thanks...

**Comment by phlptp** [comment]
cmd::unknown usually indicates the string translation for pretty printing the message was not implemented yet so in that case it just spits out the code, source and destination.  

The message codes are in https://github.com/GMLC-TDC/HELICS/blob/master/src/helics/core/ActionMessageDefintions.hpp if you want to dig further.  

You probably wouldn't see any time requests from a recorder since the messages have no reason to go to the broker in it is `source_only`  

Sounds like there might be an issue in the time requests on filters for recorders If you figure out any additional details of the issue let me know particularly if there is a scenario that fails regularly we can add a test case.

**Comment by phlptp** [comment]
The referenced message show now display a proper description associated with them.
