### ISSUE TITLE
Support Python 3.8 in anaconda

### ISSUE THREAD

**Issue by kdheepak** [GMLC-TDC/HELICS#1290]
I'm getting a number of issues to support Python 3.8, in anaconda and in our releases. It should be more straightforward to support it in pip and anaconda I imagine, I'm not sure how we would do it if we wanted to do so in the releases.

**Comment by nightlark** [comment]
There has been a binary wheel for Python 3.8 that works on reasonably recent macOS (10.9+), Linux (2010+), and Windows systems since we got the `pip` package working in version 2.4 of HELICS.

The conda package isn't getting build for Python 3.7 so this sounds specifically like an anaconda issue.

**Comment by nightlark** [comment]
Added Python 3.8 builds to [helics-conda](https://github.com/GMLC-TDC/HELICS/helics-conda), packages are uploaded.

Release builds installers that build the Python interface will be updated to use 3.8 instead of 3.6; it's not recommended and requires users to sort out search paths for Python modules on their own.

**Comment by phlptp** [comment]
Is there anything left to do on this issue @nightlark @kdheepak

**Comment by nightlark** [comment]
I think we've done all that we can do for supporting 3.8 on conda, if it still doesn't work on conda then it is likely their end.
