### ISSUE TITLE
helics_cli and web interface display config

### ISSUE THREAD

**Issue by trevorhardy** [GMLC-TDC/HELICS#1428]
The fundamental question: do we need two config files: one for helics_cli and one for the web interface? Since the web interface will be spawned from running helics_cli, couldn't we just put the necessary web interface config information in the helics_cli config?

**Comment by eberleim** [comment]
@trevorhardy I added the button for it to the web interface as a backup option, because it can be easier for visual people to do that sort of thing with a button, however, if helics-cli requires a config file anyways, there is no real reason to do it through the web interface. 
I'd say it'd be easier to simply remove the button from the web interface altogether.

**Comment by trevorhardy** [comment]
We'll plan on resolving this as a part of finalizing the implementation of the web interface and helics_cli.
