### ISSUE TITLE
Add `helicsMessageGetFlagOption` 

### ISSUE THREAD

**Issue by kdheepak** [GMLC-TDC/HELICS#1652]
There's `helicsMessageSetFlagOption`. Does it make sense to add `helicsMessageGetFlagOption`?

Also, should this enum be exposed to users? i.e. should it be part of `helics_enums.h`?

https://github.com/GMLC-TDC/HELICS/blob/742383907e5ad8af25a97d17a60985976af7c2e1/src/helics/core/flagOperations.hpp#L14-L34

**Comment by phlptp** [comment]
There is a `helicsMessageCheckFlag` which does the same thing.   Might be worth a debate on making them symmetrical I suppose but the functionality exists.

**Comment by phlptp** [comment]
And as far as the enum I would say no since those are flags for the ActionMessage used internally so I don't think it makes sense to expose that.  Especially since they are not necessarily used in the message object.   We can discuss later whether it makes sense to expose some select subset of them but probably not at this time

**Comment by kdheepak** [comment]
> There is a `helicsMessageCheckFlag` which does the same thing.

Nice. I missed that. Yeah, it might be worth making them symmetrical.
