### ISSUE TITLE
Add diagram for HELICS Terminology page in User Guide

### ISSUE THREAD

**Issue by trevorhardy** [GMLC-TDC/HELICS#2200]
[This wall of text](https://docs.helics.org/en/v3_user_guide_edits/user-guide/fundamental_topics/helics_terminology.html) could use a diagram or two to help make the ideas more digestible.

**Comment by nightlark** [comment]
Oh, that really is a wall of text.

Some observations:
- each bullet point/term has a full paragraph, most terms feel like the core definition appears in the first 1-2 sentences, but then crams in extra details that makes it harder to read in part due to...
- bulleted list packs all the text tightly together

I think giving each term its own sub-heading with the 1-2 sentence "definition" and some formatting for the extra details would be easier on the eyes, and make it much more readable.

**Comment by bpalmintier** [comment]
@trevorhardy: Your 2020 IEEE Task Force presentation (and likely others, e.g. tutorial) may have some good starting point figures.) Just came across them building another presentation.

**Comment by trevorhardy** [comment]
Fixed in commit 58d33c519.
