### ISSUE TITLE
Iterations for a single time step are not synchronised on HELICS 3.2.1 

### ISSUE THREAD

**Issue by Getnet-Ayele** [GMLC-TDC/HELICS#2408]
**Describe the bug**
Iterations out of synchronization if the federates have different speeds.

**What is the expected behavior?**
Like the time step synchronization, iterations are supposed to be synchronized.

**To Reproduce**
Here is the dummy project:
https://github.com/Getnet-Ayele/HELICS_SAInt_DummyFederates

**Environment (please complete the following information):**

- Operating System: Windows 
- Language Extension: [c#
- what compiler or setup process did you use Visual Studio 2019
- HELICS version: 

```bash
$ helics_app --version
```

**Additional context and information**
(e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by phlptp** [comment]
I will take a close look and see if I can get the example running on my system

**Comment by phlptp** [comment]
I ran it, what am I looking for in regard to what it is showing vs what you would expect?

**Comment by Getnet-Ayele** [comment]
Expected: The diverging time steps should be the same in both federates and the result should not change by repeating the simulation or by changing the delay in one of the federates. Below are some screenshots showing the diverging time steps for different simulations. 

- Setting the delay=0ms in the electric federate:

![image](https://user-images.githubusercontent.com/101350215/183034159-bfb941ee-64ce-4ef5-8df1-8004248c8d75.png)
Repeating the simulation:
![image](https://user-images.githubusercontent.com/101350215/183035131-4eaef1a5-bd20-4dc6-a794-006911f31f5b.png)

- Setting the delay =100ms in the electric federate after the time step 5.

![image](https://user-images.githubusercontent.com/101350215/183035438-bbfe62a5-1d3c-49b1-b86c-f0791f350303.png)
Repeating the simulation
![image](https://user-images.githubusercontent.com/101350215/183036344-dd0b1e3b-4e75-4e1d-a99d-94e717c70e77.png)

**Comment by phlptp** [comment]
Are you able to test this with the develop branch.  There was a minor fix related to iterations in a recent PR.  I am not 100% sure it is related but is possibly connected.

**Comment by Getnet-Ayele** [comment]
I have tested it with the "develop branch". The issue is still not resolved. 
In the updated test case (available here https://github.com/Getnet-Ayele/HELICS_SAInt_DummyFederates), only **Time-step 2** is supposed to fail (diverge). However, more time-steps are diverging when I increase the delay in the electric federate.

**Comment by eranschweitzer** [comment]
You should probably be using `helics_iteration_request_iterate_if_needed`. That will wait to see if any other Federate published new values. When you do `force_iteration` the federate immediately iterates.
The trick is to use `iterate_if_needed` until you are satisfied and want to move on and then _not publish_, thus indicating this wish to the Federation.

**Comment by phlptp** [comment]
Force_iteration does not immediately grant iteration.   At least in theory it behaves identically to iterate_if_needed except that in the case iterate_if_needed would have granted the next time step force_iteration will instead grant an additional iteration.

**Comment by eranschweitzer** [comment]
That was not what I was seeing when I was working on the iteration example. I think we even discussed this at some point. `force_iteration` in my experience had the same behavior as described by @Getnet-Ayele that the federate issuing this call begins to reiterate immediately irrespective of what else is going on in the Federation.

**Comment by Getnet-Ayele** [comment]
I tried `iterate_if_needed` option. The issue is still there. Relatively, the `force_iteration` looks slightly better. 

The reason could be that I have only two federates and they exchange data in both directions. If one is iterating, it means that it is also publishing new values at each iteration. Hence, the other federate should also be iterating and trying to get those latest values.  However, there is no way that each federate knows the iteration number of the other federate. Is there a way that `helics` counts the iteration of each federate internally for each time step?

In the code shown below, I called the `helics_iteration_request_force_iteration` just before each subscription and publication so that I can access the latest values available. If I remove those lines, the iteration misalignment gets worse. 

![image](https://user-images.githubusercontent.com/101350215/188849640-5f779aa6-2cc1-4e8e-bb61-e6bb6a57a3dd.png)

**Comment by eranschweitzer** [comment]
I think you want your time request *after* subscription and *before* publication. That should keep the iterations in sync. There is an example in his to set this up in the user guide (possibly develop branch)

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by phlptp** [comment]
Can you try this again with the new 3.3.0 release?    I am still working on translating the entire program into C to verify but there was a bug fixed that could be related in the new release since we last spoke.

**Comment by Getnet-Ayele** [comment]
Thank you for the update!

I updated the hellics library to 3.3.0. The issue is not resolved and looks the same as before.

I also tried a for loop instead of `Thread.Sleep()` to make the electric federate slower. The problem is still there.
![image](https://user-images.githubusercontent.com/101350215/191036296-a22ed07f-c364-487d-8e84-c0b19d5bb697.png)

**Comment by eranschweitzer** [comment]
Would it be possible for you to provide some sort of log output for how the federates are moving through time and exchanging information?

`iterate_if_needed` really _should_ be the call you use, so the fact that `force_iteration` seems needed is an indication that something may not be set up correctly.

**Comment by Getnet-Ayele** [comment]
> Would it be possible for you to provide some sort of log output for how the federates are moving through time and exchanging information?
> 
> `iterate_if_needed` really _should_ be the call you use, so the fact that `force_iteration` seems needed is an indication that something may not be set up correctly.

@eranschweitzer 
Here are the log files for different simulations. Additional log files of the results are now made available in the [Output](https://github.com/Getnet-Ayele/HELICS_SAInt_DummyFederates/tree/main/HelicsDotNet/outputs) folder.

The reference log files are taken from the simulation which gave me better results, but they do not necessarily mean that the iterations are synchronized.

Let me know if you need further information about the log file or to run the dummy federates again.

**Comment by eranschweitzer** [comment]
@Getnet-Ayele, thank you for sharing those.
Here is my suspicion about at least some of what is going on.

1. I think you might not be logging things quite correctly. The reason is in the [iterate if needed log](https://github.com/Getnet-Ayele/HELICS_SAInt_DummyFederates/blob/main/HelicsDotNet/outputs/Log_Iterate_If_Needed.txt). Your `iter` counter appears to continue increasing even when your federates get `iteration status: 0` which means `NEXT_STEP`, which means time should actually be progressing. 
2. Based on the order of things in the logs, and what you posted before it appears that your federate code is structured as follows:
* call `request_time`
* call `get_subscriptions`
* process
* call `send_publications`
The issue is that you really should be publishing _before_ calling `request_time` as the presence of new data is what tells HELICS to return the `ITERATING` status.

There is some general information about how to structure iteration [here](https://docs.helics.org/en/latest/user-guide/advanced_topics/iteration.html), including a [pseudo-code example](https://docs.helics.org/en/latest/user-guide/advanced_topics/iteration.html#example-iterative-federate-psuedo-code).
While these are more "python like" the concept should be the same.

There is further an example on how to set up iteration [here](https://docs.helics.org/en/latest/user-guide/examples/advanced_examples/advanced_iteration.html) and the code is [here](https://github.com/GMLC-TDC/HELICS-Examples/tree/main/user_guide_examples/advanced/advanced_iteration).
These examples are also of two different Federates, so there is actually a good deal of similarity between that and your problem (other than the examples are in Python and not C#).

I would strongly encourage you to take a look at those examples and compare their structure to yours.
If it is _not_ the same, consider reworking your federate structure and see if that works.
If they _are_ the same...then we probably do have a bug 😅

**Comment by Getnet-Ayele** [comment]
@eranschweitzer, thank you for your detailed feedback!

I will go through your suggestions and will let you know the outcome.

**Comment by phlptp** [comment]
I will look into that, It is possible some of the recent changes caused that property to not work correctly.
