### ISSUE TITLE
`--profiler=profile.txt` should write to `profile.txt` in `write` mode instead of `append` mode

### ISSUE THREAD

**Issue by kdheepak** [GMLC-TDC/HELICS#2411]
It would be nice if when I ran the following:

```
helics_broker -f3 --profiler=profile.txt
```

and a `profile.txt` file already exists, it writes to the file as though it were a new file, instead of writing to the file in append mode.

**Comment by phlptp** [comment]
Doing this suggestion could be rather complex and problematic in some cases.  The way it was designed multiple different federates could write to the output file so it must append.  And the buffer is written periodically meaning it must append in that case as well otherwise you will only get partial results.   So I think appending must be the default.  

What could be done is if the file has a special character as the first character of the file name the file will be reset when the profiler is started  for example
```sh
helics_broker -f3 --profiler=-profile.txt
```

It also might be worth adding a divider comment that makes a clear separation when it first starts.
