### ISSUE TITLE
loglevel: 1 not in {summary,none,connections,no_print,profiling,interfaces,error,timing,warning,data,debug,trace}

### ISSUE THREAD

**Issue by LBorden24** [GMLC-TDC/HELICS#2662]
Attempting to write my first custom HELICS co-simulation. Upon executing the program, one of my files fails with the Exception in the screenshot below. I have not been able to find what this error message means making it hard to fix. If anyone can explain, or point me to documentation on what this error means and how to fix it that would be appreciated. Thanks
<img width="960" alt="helics loglevel" src="https://github.com/GMLC-TDC/HELICS/assets/153466401/fbe08d10-da43-425c-a650-90cc687a5e59">

**Comment by trevorhardy** [comment]
A little while back we changed the way we designate log levels from using numerical values to using strings. The error message is indicating that you need to use one of the strings indicated in the error message (_e.g._ "debug", "warning") instead of a numeric value. Without knowing your code I can't say specifically where you're trying to set the logging level but look through the federate code, federate config JSONs (if you're using them) and the runner JSONs (if you're using them).

**Comment by LBorden24** [comment]
Understood, thank you. That has resolved my problem. I am now getting the new error message below, but at least that's some amount of progress
![image](https://github.com/GMLC-TDC/HELICS/assets/153466401/fba92efd-88e5-43cf-a11d-2e478b39d4d5)

**Comment by trevorhardy** [comment]
I'm guessing that is a JSON validation error. Try running your JSON config through a JSON validator online to see if it thinks the config file is OK.

**Comment by LBorden24** [comment]
Yeah, I had a bracket in the wrong spot. Easy enough fix. Thanks for your help.
