### ISSUE TITLE
vcpkg library integration

### ISSUE THREAD

**Issue by phlptp** [GMLC-TDC/HELICS#291]
Build integration for the [vcpkg package manager](https://github.com/Microsoft/vcpkg)

this is now available on Windows/Linux/mac

**Comment by nightlark** [comment]
There are issues linking with parts of the Boost library built by vcpkg (after initial attempts at fixing, it is likely easier to do some refactoring so that the IPC core can be disabled in vcpkg builds). The submission process for getting a package will also take some time to get approval for.  For this package, I think it might be best to move it to a 2.X (1?) milestone.

**Comment by nightlark** [comment]
I don't think removing the dependency on compiled Boost libraries will help -- removing the use of the boost ptime header might help, since it isn't able to find some gregorian calendar related functions that it wants to link with (already telling Boost not to link with date_time). But then I also tried enabling linking with date_time and it still couldn't find the functions, so it might be a problem with the vcpkg boost ipc package.

**Comment by phlptp** [comment]
Well the new IPC queue stuff should do that since I think the ptime is only used for the IPC queue timeout.  The new one would use <chrono>

**Comment by nightlark** [comment]
It looks like the rest of that got cut off (std::chrono?). I'll try removing the ptime code to see if that will resolve the linking errors.

**Comment by nightlark** [comment]
Oh. Actually, I just looked at the change history -- apparently I did try removing the ptime header and code, and it still didn't work. So it is probably something to do with the boost ipc package being somehow different than when we compile it outside of vcpkg.

**Comment by phlptp** [comment]
@nightlark  can this be considered done?

**Comment by nightlark** [comment]
For now this can be considered done based on vcpkg adding features that allow it to work without adding an entry to the main vcpkg registry.
