### ISSUE TITLE
Use Checks from Travis CI

### ISSUE THREAD

**Issue by phlptp** [GMLC-TDC/HELICS#307]
Just saw a new feature 
https://blog.travis-ci.com/2018-05-07-announcing-support-for-github-checks-api-on-travis-ci-com

Travis integrated Checks inside Github.  
Is this something that we can do and is useful?

**Comment by nightlark** [comment]
We should probably switch over, it sounds like the checks API and the GitHub app will be the preferred way over what they were using to integrate with GH before.

It looks like it will involve installing the Travis CI app for GMLC-TDC from the GitHub marketplace (https://github.com/marketplace/travis-ci) and possibly changing some repository settings.

**Comment by phlptp** [comment]
Ok Lets get the 1.1 release out tomorrow then do what we need to, to make the switch over.

**Comment by nightlark** [comment]
Alright, so I tried migrating an existing repository to see what happens; what I've found is that since we are already using the legacy services integration, we need to migrate to travis-ci.com for the GitHub Apps integration. The response I got from support is that they could do the migration right now, but that build history so far on travis-ci.org will be lost, otherwise, around the end of Q2 2018 there will be the option to migrate open source repositories with build history (presumably when GitHub stops running their services api, that migration will happen automatically towards the end of 2018).

I've asked support to notify me when the option to migrate repositories with build history becomes available, after which it should be safe to remove Travis CI from the services section of https://github.com/GMLC-TDC/HELICS-src/settings/installations

**Comment by phlptp** [comment]
We will need to get Travis running with HELICS-FMI fairly soon,  I don't care about the history of that project so we could just try it on that Repo, to see if there are any issues.  And we put this issue ON HOLD until we the migration tool is available.

**Comment by nightlark** [comment]
@phlptp maybe we can try migrating homebrew-helics using https://travis-ci.com/organizations/GMLC-TDC/migrate and see if they have history migration or not

**Comment by phlptp** [comment]
Looks like this is mostly happening without direct intervention as travis switches over, so I am going to close the issue, and we can open a new one if something specific comes up
