### ISSUE TITLE
Rename repo  HELICS-src to HELICS

### ISSUE THREAD

**Issue by phlptp** [GMLC-TDC/HELICS#692]
the -src in the Repo name seems a bit odd.  What would be implications and thoughts about changing it to just HELICS?

**Comment by kdheepak** [comment]
Nothing major I think, since [`https://github.com/GMLC-TDC/HELICS-src`](https://github.com/GMLC-TDC/HELICS-src) will redirect to [`https://github.com/GMLC-TDC/HELICS`](https://github.com/GMLC-TDC/HELICS) as long as we don't create a repo in this organization called `HELICS-src`. Search engines will pick it up as a redirect and update the links to the new page eventually. If we do create a repo with that name then it naturally won't redirect automatically any more. We'll also have to update all the packaging recipes, documentation to link to the correct location. Since documentation is hosted on [`https://helics.readthedocs.io/en/latest/`](https://helics.readthedocs.io/en/latest/), that will be fine too.

I'm not sure what happens if anyone visits [`http://gmlc-tdc.github.io/HELICS-src/`](http://gmlc-tdc.github.io/HELICS-src/) after we change the URL. I'm assuming that redirects too, but if it doesn't we won't be able to fix that (because the only way to fix it would be to create a repo called `HELICS-src` which will break the redirects of the source code repo).

**Comment by phlptp** [comment]
If we are going to do it I want to do it at the 2.1 release so we would be updating all the packaging repos anyway.

**Comment by phlptp** [comment]
@bpalmintier @jcfuller1 @afisher1 @trevorhardy  What do you think of this proposal

**Comment by trevorhardy** [comment]
Sounds fine to me.

**Comment by bpalmintier** [comment]
Agree. Like the simpler naming

**Comment by phlptp** [comment]
Lets make the change on Wednesday Morning.   @nightlark could you go through the repo and docs and shortly after make a PR to make the changes to the necessary links and CI system build configs.

**Comment by trevorhardy** [comment]
I'm assuming I'll have to do the same thing for the User Guide?

**Comment by phlptp** [comment]
@trevorhardy Can you coordinate with Ryan,  it may be pretty quick just to do a bulk search so hopefully won't take that much effort.

**Comment by nightlark** [comment]
Branches with the updated name are ready.

**Comment by nightlark** [comment]
This might also be an opportunity to close #307

**Comment by trevorhardy** [comment]
@nightlark, did you catch any URLs in the User Guide?

**Comment by nightlark** [comment]
Probably, check the `update-helics-src-url` branch.

**Comment by trevorhardy** [comment]
I'm not seeing any "GMLC-TDC/Helics-src/..." and I am seeing "GMLC-TDC/HELICS/..." so I think we're good.

**Comment by phlptp** [comment]
Repo was moved 6/19/2019
