### ISSUE TITLE
make install should add helics `\bin` to PATH (OSX?)

### ISSUE THREAD

**Issue by bpalmintier** [GMLC-TDC/HELICS#766]
When compiling from source on OSX (haven't tested elsewhere), `make install` should also add the `\path\to\helics_install\bin` folder to the users PATH.

Workaround: Could be we add a step for the user to manually add in `.bashrc`

**Comment by nightlark** [comment]
The documentation for macOS installation has been updated to include some basic info on PATH and links to resources for more information so that users can add a custom install `bin` folder to PATH either temporarily or permanently based on what their use case.

We don't want to be automatically clobbering the PATH a user has set up.  If the user installs to a system location (e.g. `/usr`, `/usr/local`) then it should already be on the PATH, so this only comes up when using a custom install location; it's up to the user to decide if they want it added to the PATH (temporary or persistent) if they want it at all based on their use case. Also, any situation with side-by-side installs to different locations would quickly make it confusing which version is getting run.

The doc update includes a resource that talks about adding things to PATH from a shell profile -- macOS Catalina switched from bash to zsh as the default shell.
