### ISSUE TITLE
clang-format githook unusable on windows

### ISSUE THREAD

**Issue by phlptp** [GMLC-TDC/HELICS#987]
**Describe the bug**
The clang-format git hook is problematic on windows and should be disabled
typical windows usage is with tortoiseGit which does not have have a way to bypass the hook.  
Also turning it off does not remove the hook
if multiple builds are with the same source repo the hook is enabled on all builds.  As is it is essentially rendering it impossible to commit since running clang-format doesn't seem to clear up the restriction for unknown reasons.  

**What is the expected behavior?**
 What is the motivation / use case for changing the behavior?
if the hook is installed via cmake it needs to be removable via cmake configuration if the option is deselected.  It should be off by default on windows, and possibly all systems unless it is controlled on a per build basis, 

Or it should be warning only not block commits.  

**Environment (please complete the following information):**
 - Operating System:Windows
```

**Comment by phlptp** [comment]
Is there a reason the githook can't just run clang-format and commit the updated files instead of just showing a warning and blocking the commit?

**Comment by eberleim** [comment]
@phlptp I actually tried to have it do self-run on the first attempt, and discovered that while that method had previously worked, something in how git handles pre-commit hooks caused an order-operation type error, where they were staged, but not considered part of the currently initiated commit, and as such, would require a separate commit to be executed and amended. 

The commit hook itself requires a bash shell and clang-format exist, which is likely the problem here, since those paths may exist inside a terminal, but not necessarily inside TortoiseGit and other interfaces. I'll create a check to verify the existence of the application inside of the hook as well, although it does unfortunately reduce the value of this hook, it should at least make it no longer destructive. 

I've made a change to verify clang-format exists in git's environment and the warning will no longer cause the pre-commit to block, and will simply notify the user. Unfortunately the per-build in the repo option is not really possible, since all CMake is doing is setting a git flag. The CMake generator would need to be re-run before each compile (possible, but hard to guarantee).

**Comment by phlptp** [comment]
It might be possible to make a target using cmake that runs a script like you would have done in the hook, possibly even using similar code.  Then that would be available from cmake, but using the same logic as the githook.    So the githook can issue a warning with instructions to run a particualar target so a user wouldn't have to figure out how to manually execute the command.
